language:  generic

notifications:
  slack:
    rooms:
      - apacheexpress:9z2IfvxZfENp0TFmiYCgyUKz

matrix:
    include:
        - os:   Linux
          dist: trusty
          env:  SWIFT_SNAPSHOT_NAME="https://swift.org/builds/swift-4.2.4-release/ubuntu1404/swift-4.2.4-RELEASE/swift-4.2.4-RELEASE-ubuntu14.04.tar.gz"
          sudo: required
        - os:   Linux
          dist: trusty
          env:  SWIFT_SNAPSHOT_NAME="https://swift.org/builds/swift-5.0-release/ubuntu1404/swift-5.0-RELEASE/swift-5.0-RELEASE-ubuntu14.04.tar.gz"
          sudo: required
        - os:   Linux
          dist: xenial
          env:  SWIFT_SNAPSHOT_NAME="https://swift.org/builds/swift-5.2-release/ubuntu1604/swift-5.2-RELEASE/swift-5.2-RELEASE-ubuntu16.04.tar.gz"
          sudo: required
        #- os:   osx # fails in compiler
        #  osx_image: xcode10.1
        - os:   osx
          osx_image: xcode10.2

before_install:
    - ./.travis.d/before-install.sh

install:
    - ./.travis.d/install.sh

script:
    - export PATH="$HOME/usr/bin:$PATH"
    - swift build -c release
    - swift build -c debug

